#nbs
testList = []
(testList.append(34,))
print(testList)
(testList.append(22))
print(testList)
(testList.sort())
print(testList)
(testList.pop())
print(testList)
(testList.insert(0, 22))
print(testList)
(testList.insert(1, 55))
print(testList)
(testList.pop(1))
print(testList)
(testList.remove(22))
print(testList)
(testList.remove(55))
print(testList)
